'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { dashboardFetch } from '../lib/api';
import { Input, PageIntro, PrimaryButton, StatusPill } from './ui';

interface ApiKeyRecord { id: string; name: string; prefix: string; permissions: string[]; status: string; expiresAt: string | null; lastUsedAt: string | null; createdAt: string }
const permissions = ['events:write', 'notifications:read', 'notifications:write', 'templates:read', 'templates:write', 'analytics:read', 'webhooks:manage', 'workflows:manage', 'users:manage', 'devices:manage'];

export function ApiKeyWorkspace() {
  const [items, setItems] = useState<ApiKeyRecord[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [secret, setSecret] = useState<string | null>(null);
  const load = useCallback(async () => { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; try { setItems(await dashboardFetch<ApiKeyRecord[]>('/v1/dashboard/api-keys', token)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load API keys'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const selected = permissions.filter((permission) => form.get(`permission-${permission}`) === 'on'); if (!selected.length) { setError('Select at least one permission.'); return; } setBusy(true); setError(''); try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) throw new Error('Sign in again to create an API key.'); const created = await dashboardFetch<{ key: string }>('/v1/api-keys', token, { method: 'POST', body: { name: form.get('name'), permissions: selected, environment: form.get('environment'), ...(form.get('expires_at') ? { expires_at: new Date(String(form.get('expires_at'))).toISOString() } : {}) } }); setSecret(created.key); formElement.reset(); setOpen(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create API key'); } finally { setBusy(false); } };
  const revoke = async (id: string) => { if (!window.confirm('Revoke this API key? Clients using it will lose access immediately.')) return; try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; await dashboardFetch<void>(`/v1/api-keys/${id}`, token, { method: 'DELETE' }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to revoke API key'); } };
  return <><PageIntro eyebrow="Developer access" title="API keys" description="Issue least-privilege keys for external applications. Raw values are revealed once and cannot be recovered." action={<PrimaryButton onClick={() => setOpen((value) => !value)}>{open ? 'Close form' : 'Create API key'}</PrimaryButton>} />{error && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}{secret && <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Copy this key now. It will not be shown again.</p><code className="mt-2 block overflow-auto rounded bg-white p-2 text-xs">{secret}</code><button onClick={() => setSecret(null)} className="mt-3 font-semibold text-amber-800">I saved it</button></div>}
    {open && <form onSubmit={submit} className="mb-6 rounded-xl border border-indigo-100 bg-indigo-50/50 p-5"><div className="grid gap-4 md:grid-cols-2"><Input label="Key name" name="name" placeholder="Orders production" required /><label className="block text-sm font-medium text-slate-700">Environment<select name="environment" className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="test">Test</option><option value="live">Live</option></select></label><Input label="Expiry (optional)" name="expires_at" type="datetime-local" /></div><fieldset className="mt-4"><legend className="text-sm font-medium text-slate-700">Permissions</legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{permissions.map((permission, index) => <label key={permission} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><input name={`permission-${permission}`} type="checkbox" defaultChecked={index === 0} />{permission}</label>)}</div></fieldset><div className="mt-5"><PrimaryButton type="submit" disabled={busy}>{busy ? 'Creating…' : 'Create key'}</PrimaryButton></div></form>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Key</th><th className="px-5 py-3">Permissions</th><th className="px-5 py-3">Last used</th><th className="px-5 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-semibold text-slate-900">{item.name}</p><code className="text-xs text-slate-500">{item.prefix}…</code></td><td className="max-w-sm px-5 py-4"><div className="flex flex-wrap gap-1">{item.permissions.map((permission) => <span key={permission} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">{permission}</span>)}</div></td><td className="whitespace-nowrap px-5 py-4 text-slate-500">{item.lastUsedAt ? new Date(item.lastUsedAt).toLocaleString() : 'Never'}</td><td className="px-5 py-4"><StatusPill value={item.status} /></td><td className="px-5 py-4">{item.status === 'ACTIVE' && <button onClick={() => void revoke(item.id)} className="text-sm font-semibold text-rose-600">Revoke</button>}</td></tr>)}{!items.length && <tr><td colSpan={5} className="px-5 py-12 text-center text-slate-500">No API keys yet.</td></tr>}</tbody></table></div></section></>;
}
