'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { dashboardFetch } from '../lib/api';
import { Input, PageIntro, PrimaryButton, Select, StatusPill, Textarea } from './ui';

interface NotificationRecord { id: string; title: string; body: string; priority: string; status: string; createdAt: string; user: { externalId: string; email: string | null }; deliveries: Array<{ id: string; channel: string; status: string }> }
const channelOptions = ['EMAIL', 'PUSH', 'WEBHOOK'];

export function NotificationWorkspace() {
  const [items, setItems] = useState<NotificationRecord[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; try { const data = await dashboardFetch<NotificationRecord[]>('/v1/dashboard/notifications', token); setItems(data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load notifications'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const channels = channelOptions.filter((channel) => form.get(`channel-${channel}`) === 'on'); if (!channels.length) { setError('Choose at least one channel.'); return; } setBusy(true); setError(''); try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) throw new Error('Sign in again to send a notification.'); await dashboardFetch('/v1/dashboard/notifications', token, { method: 'POST', body: { user_id: form.get('user_id'), notification: { title: form.get('title'), message: form.get('message'), priority: form.get('priority'), category: form.get('category') }, channels, ...(form.get('scheduled_at') ? { scheduled_at: new Date(String(form.get('scheduled_at'))).toISOString() } : {}) } }); setOpen(false); setMessage('Notification accepted and queued for delivery.'); formElement.reset(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to queue notification'); } finally { setBusy(false); } };
  const cancel = async (id: string) => { if (!window.confirm('Cancel this notification before delivery?')) return; try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; await dashboardFetch<void>(`/v1/dashboard/notifications/${id}/cancel`, token, { method: 'POST' }); setMessage('Notification cancelled.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to cancel notification'); } };
  return <><PageIntro eyebrow="Delivery operations" title="Notifications" description="Create one-off messages, inspect their channel state, and stop queued deliveries before they are sent." action={<PrimaryButton onClick={() => setOpen((value) => !value)}>{open ? 'Close composer' : 'New notification'}</PrimaryButton>} />
    {message && <div className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{message}</div>}{error && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    {open && <form onSubmit={submit} className="mb-6 rounded-xl border border-indigo-100 bg-indigo-50/50 p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><Input label="External user ID" name="user_id" placeholder="user_123" required /><Input label="Title" name="title" placeholder="Payment successful" required /><div className="md:col-span-2"><Textarea label="Message" name="message" placeholder="Your payment of NPR 2,500 was successful." required /></div><Select label="Priority" name="priority" defaultValue="NORMAL"><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="CRITICAL">Critical</option></Select><Input label="Category" name="category" defaultValue="transactional" required /><Input label="Schedule (optional)" name="scheduled_at" type="datetime-local" /><fieldset className="md:col-span-2"><legend className="text-sm font-medium text-slate-700">Channels</legend><div className="mt-2 flex flex-wrap gap-3">{channelOptions.map((channel) => <label key={channel} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><input name={`channel-${channel}`} type="checkbox" defaultChecked={channel === 'EMAIL'} />{channel.toLowerCase()}</label>)}</div></fieldset></div><div className="mt-5"><PrimaryButton type="submit" disabled={busy}>{busy ? 'Queueing…' : 'Queue notification'}</PrimaryButton></div></form>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Message</th><th className="px-5 py-3">Recipient</th><th className="px-5 py-3">Channels</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Created</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="max-w-sm px-5 py-4"><p className="font-semibold text-slate-900">{item.title}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{item.body}</p></td><td className="px-5 py-4 text-slate-600"><p>{item.user.externalId}</p><p className="text-xs text-slate-400">{item.user.email ?? 'No email'}</p></td><td className="px-5 py-4"><div className="flex flex-wrap gap-1">{item.deliveries.map((delivery) => <span key={delivery.id} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">{delivery.channel.toLowerCase()}</span>)}</div></td><td className="px-5 py-4"><StatusPill value={item.status} /></td><td className="whitespace-nowrap px-5 py-4 text-slate-500">{new Date(item.createdAt).toLocaleString()}</td><td className="px-5 py-4">{['QUEUED', 'CREATED', 'RETRYING'].includes(item.status) && <button onClick={() => void cancel(item.id)} className="text-sm font-semibold text-rose-600 hover:text-rose-700">Cancel</button>}</td></tr>)}{!items.length && <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">No notifications have been created yet.</td></tr>}</tbody></table></div></section></>;
}
