'use client';

import { useEffect, useState } from 'react';
import { dashboardFetch } from '../lib/api';

interface Overview { total_notifications: number; sent: number; delivered: number; failed: number; pending: number; delivery_rate: number; failure_rate: number; channel_breakdown: Array<{ channel: string; status: string; _count: { _all: number } }>; recent_events: Array<{ id: string; eventType: string; status: string; createdAt: string }>; recent_failures: Array<{ id: string; channel: string; errorCode: string | null; errorMessage: string | null; createdAt: string }> }
const metricLabels: Array<[keyof Pick<Overview, 'total_notifications' | 'sent' | 'delivered' | 'failed' | 'pending'>, string, string]> = [['total_notifications', 'Notifications today', 'text-indigo-600'], ['sent', 'Sent', 'text-sky-600'], ['delivered', 'Delivered', 'text-emerald-600'], ['failed', 'Failed', 'text-rose-600'], ['pending', 'Pending', 'text-amber-600']];

export function OverviewPanel() {
  const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState('');
  useEffect(() => { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; dashboardFetch('/v1/dashboard/overview', token).then((value) => setData(value as Overview)).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load dashboard')); }, []);
  if (error) return <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!data) return <div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading live notification metrics…</div>;
  return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metricLabels.map(([key, label, color]) => <article key={key} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className={`mt-3 text-3xl font-bold ${color}`}>{data[key].toLocaleString()}</p></article>)}</section><section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Delivery performance</h2><span className="text-sm text-slate-500">Today</span></div><div className="mt-6 grid grid-cols-2 gap-4"><div className="rounded-lg bg-emerald-50 p-4"><p className="text-sm text-emerald-700">Delivery rate</p><p className="mt-1 text-3xl font-bold text-emerald-800">{data.delivery_rate}%</p></div><div className="rounded-lg bg-rose-50 p-4"><p className="text-sm text-rose-700">Failure rate</p><p className="mt-1 text-3xl font-bold text-rose-800">{data.failure_rate}%</p></div></div><div className="mt-6 space-y-2">{data.channel_breakdown.length ? data.channel_breakdown.map((item, index) => <div key={`${item.channel}-${item.status}-${index}`} className="flex justify-between rounded-lg border border-slate-100 px-3 py-2 text-sm"><span>{item.channel} · {item.status}</span><strong>{item._count._all.toLocaleString()}</strong></div>) : <p className="text-sm text-slate-500">No delivery data in this period.</p>}</div></article><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Recent failures</h2><div className="mt-4 space-y-3">{data.recent_failures.length ? data.recent_failures.map((failure) => <div key={failure.id} className="rounded-lg bg-rose-50 p-3 text-sm"><p className="font-medium text-rose-900">{failure.channel} · {failure.errorCode ?? 'Provider error'}</p><p className="mt-1 line-clamp-2 text-rose-700">{failure.errorMessage ?? 'No provider detail'}</p></div>) : <p className="text-sm text-slate-500">No recent failures.</p>}</div></article></section><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Recent events</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="pb-2">Event</th><th className="pb-2">Status</th><th className="pb-2">Received</th></tr></thead><tbody>{data.recent_events.map((event) => <tr key={event.id} className="border-t border-slate-100"><td className="py-3 font-medium">{event.eventType}</td><td className="py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{event.status}</span></td><td className="py-3 text-slate-500">{new Date(event.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></section></div>;
}
