'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { dashboardFetch } from '../lib/api';
import { Input, PageIntro, PrimaryButton, Select, StatusPill, Textarea } from './ui';

interface TemplateRecord { id: string; name: string; eventType: string; channel: string; subject: string | null; body: string; language: string; version: number; status: string; updatedAt: string }

export function TemplateWorkspace() {
  const [items, setItems] = useState<TemplateRecord[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; try { setItems(await dashboardFetch<TemplateRecord[]>('/v1/dashboard/templates', token)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load templates'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) throw new Error('Sign in again to create a template.'); await dashboardFetch('/v1/dashboard/templates', token, { method: 'POST', body: { name: form.get('name'), event_type: form.get('event_type'), channel: form.get('channel'), subject: form.get('subject') || undefined, body: form.get('body'), language: form.get('language'), status: form.get('status') } }); event.currentTarget.reset(); setOpen(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create template'); } finally { setBusy(false); } };
  return <><PageIntro eyebrow="Content library" title="Templates" description="Create versioned channel content with safe variables such as {{user.name}} and {{data.order_id}}." action={<PrimaryButton onClick={() => setOpen((value) => !value)}>{open ? 'Close editor' : 'New template'}</PrimaryButton>} />{error && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    {open && <form onSubmit={submit} className="mb-6 rounded-xl border border-indigo-100 bg-indigo-50/50 p-5"><div className="grid gap-4 md:grid-cols-2"><Input label="Template name" name="name" placeholder="Order confirmation" required /><Input label="Event type" name="event_type" placeholder="order.created" required /><Select label="Channel" name="channel"><option value="EMAIL">Email</option><option value="PUSH">Push</option><option value="WEBHOOK">Webhook</option></Select><Select label="Status" name="status" defaultValue="DRAFT"><option value="DRAFT">Draft</option><option value="ACTIVE">Active</option></Select><Input label="Subject" name="subject" placeholder="Order {{data.order_id}} received" /><Input label="Language" name="language" defaultValue="en" required /><div className="md:col-span-2"><Textarea label="Body" name="body" placeholder="Hello {{user.name}}, your order is confirmed." required /></div></div><div className="mt-5"><PrimaryButton type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save template'}</PrimaryButton></div></form>}
    <section className="grid gap-4 lg:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-slate-900">{item.name}</p><p className="mt-1 text-sm text-indigo-600">{item.eventType} · {item.channel.toLowerCase()}</p></div><StatusPill value={item.status} /></div><p className="mt-4 text-sm font-medium text-slate-700">{item.subject ?? 'No subject'}</p><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-slate-500">{item.body}</p><div className="mt-4 flex justify-between border-t border-slate-100 pt-3 text-xs text-slate-400"><span>{item.language.toUpperCase()} · v{item.version}</span><span>Updated {new Date(item.updatedAt).toLocaleDateString()}</span></div></article>)}{!items.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 lg:col-span-2">No templates yet. Create an active template to route matching events.</div>}</section></>;
}
