'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { dashboardFetch } from '../lib/api';
import { Input, PageIntro, PrimaryButton, Select, StatusPill } from './ui';

interface WorkflowRecord { id: string; name: string; eventType: string; status: string; definition: { nodes?: Array<{ type?: string; channels?: string[]; category?: string }> }; updatedAt: string }

export function WorkflowWorkspace() {
  const [items, setItems] = useState<WorkflowRecord[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) return; try { setItems(await dashboardFetch<WorkflowRecord[]>('/v1/dashboard/workflows', token)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load workflows'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const channels = ['EMAIL', 'PUSH', 'WEBHOOK'].filter((channel) => form.get(`channel-${channel}`) === 'on'); if (!channels.length) { setError('Choose at least one routing channel.'); return; } setBusy(true); setError(''); try { const token = window.localStorage.getItem('notification-dashboard-token'); if (!token) throw new Error('Sign in again to create a workflow.'); await dashboardFetch('/v1/dashboard/workflows', token, { method: 'POST', body: { name: form.get('name'), event_type: form.get('event_type'), status: form.get('status'), definition: { nodes: [{ type: 'EVENT' }, { type: 'SEND_NOTIFICATION', category: form.get('category'), channels, priority: form.get('priority') }, { type: 'END' }] } } }); formElement.reset(); setOpen(false); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create workflow'); } finally { setBusy(false); } };
  return <><PageIntro eyebrow="Event routing" title="Workflows" description="Define the notification route for an event. This MVP activates the selected send step and preserves a JSON shape for future visual automation." action={<PrimaryButton onClick={() => setOpen((value) => !value)}>{open ? 'Close builder' : 'New workflow'}</PrimaryButton>} />{error && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    {open && <form onSubmit={submit} className="mb-6 rounded-xl border border-indigo-100 bg-indigo-50/50 p-5"><div className="grid gap-4 md:grid-cols-2"><Input label="Workflow name" name="name" placeholder="Payment success" required /><Input label="Event type" name="event_type" placeholder="payment.success" required /><Input label="Category" name="category" defaultValue="transactional" required /><Select label="Priority" name="priority" defaultValue="NORMAL"><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="CRITICAL">Critical</option></Select><Select label="Status" name="status" defaultValue="ACTIVE"><option value="ACTIVE">Active</option><option value="DRAFT">Draft</option></Select><fieldset><legend className="text-sm font-medium text-slate-700">Delivery channels</legend><div className="mt-2 flex gap-3">{['EMAIL', 'PUSH', 'WEBHOOK'].map((channel) => <label key={channel} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><input name={`channel-${channel}`} type="checkbox" defaultChecked={channel === 'EMAIL'} />{channel.toLowerCase()}</label>)}</div></fieldset></div><div className="mt-5"><PrimaryButton type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save workflow'}</PrimaryButton></div></form>}
    <section className="space-y-3">{items.map((item) => { const nodes = item.definition?.nodes ?? []; const send = nodes.find((node) => node.type === 'SEND_NOTIFICATION'); return <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold text-slate-900">{item.name}</h3><p className="mt-1 text-sm text-indigo-600">{item.eventType}</p></div><StatusPill value={item.status} /></div><div className="mt-5 flex flex-wrap items-center gap-2 text-sm">{nodes.map((node, index) => <span key={`${node.type}-${index}`} className="rounded-lg bg-slate-100 px-3 py-2 font-medium text-slate-700">{node.type?.replaceAll('_', ' ')}</span>)}{send?.channels?.map((channel) => <span key={channel} className="rounded-lg bg-indigo-50 px-3 py-2 text-indigo-700">{channel.toLowerCase()}</span>)}</div><p className="mt-4 text-xs text-slate-400">Updated {new Date(item.updatedAt).toLocaleString()}</p></article>; })}{!items.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No workflows yet. Create one to make an event route explicit.</div>}</section></>;
}
